global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'legacy-refactor-api'
    static_configs:
      - targets: ['legacy-refactor-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'legacy-refactor-dashboard'
    static_configs:
      - targets: ['legacy-refactor-dashboard:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093